[theme]
base = "light"
primaryColor = "#2B6CB0"
backgroundColor = "#F3F4F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2933"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
